#!/bin/bash
#
# Maintainer script for publishing releases.

set -e

py_version=$(python3 setup.py --version)
deb_version=$(dpkg-parsechangelog -S Version)

if [[ "$py_version" != "$deb_version" ]]; then
    echo "version mismatch - py: $py_version != deb: $deb_version"
    exit 1
fi

gbp buildpackage --git-tag-only
debuild
debrelease
git push --tags
