#!/bin/bash
#
# Maintainer script for publishing releases.

set -e

script_dir=$(dirname $(readlink -f $0))

source=$(dpkg-parsechangelog -S Source)
version=$(dpkg-parsechangelog -S Version)
arch=$(dpkg-architecture --query DEB_HOST_ARCH)

debuild -d
debsign ../${source}_${version}_${arch}.changes
dput -c ${script_dir}/dput.cf skywrangler ../${source}_${version}_${arch}.changes
ssh ablerobots@archive.ablerobots.com -C 'reprepro -b reprepro/skywrangler processincoming upload'
gbp buildpackage --git-tag-only
git push --tags
